---
name: "EnOcean MQTT (Kessel Staufix)"
description: "EnOcean to MQTT bridge with Kessel Staufix Control support"
url: "https://github.com/ESDN83/HA_enoceanmqtt-addon"
version: "1.1.7"
slug: "ha_enoceanmqtt_kessel"
homeassistant: "2024.2.0"
init: false
uart: true
hassio_api: true
homeassistant_api: true
services:
  - "mqtt:need"
map:
  - "config:rw"
arch:
  - aarch64
  - amd64
options:
  device_file: "/data/custom_configs/enoceanmqtt.devices"
  enocean_port: ""
  enocean_tcp: ""
  mapping_files:
    mapping_file: ""
    eep_file: "/data/custom_configs/EEP.xml"
  logging:
    log_file: "/config/enoceanmqtt.log"
    debug: false
    log_packets: false
  mqtt:
    host: ""
    port: ""
    user: ""
    pwd: ""
    discovery_prefix: "homeassistant"
    prefix: "enoceanmqtt"
    client_id: "enocean_gateway"
    keepalive: 60
schema:
  device_file: "str"
  enocean_port: "device(subsystem=tty)?"
  enocean_tcp: "match(tcp:.+:[0-9]+|^$)?"
  mapping_files:
    mapping_file: "str?"
    eep_file: "str?"
  logging:
    log_file: "str?"
    debug: "bool?"
    log_packets: "bool?"
  mqtt:
    host: "str?"
    port: "str?"
    user: "str?"
    pwd: "password?"
    discovery_prefix: "str"
    prefix: "str"
    client_id: "str"
    keepalive: "int"
